config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "admin/authors#index"    
  # root "authors#index"
  # get '/authors', to: 'authors#index', as: :getname
  # get '/authors/:id', to: 'authors#show'
  # get '/authors/new', to: 'authors#new'

  # resources :authors
  
  namespace :admin do
    resources :authors
  end
  # namespace :admin do 
  #   resources :authors
  # end
  # scope module: 'admin' do
  #   resources :authors
  # end
  # scope shallow_path: "se" do
    # resources :authors do 
    #   resources :books ,shallow: true
    # end
  # end
  # scope shallow_prefix: "se" do
  #   resources :authors do 
  #     resources :books ,shallow: true
  #   end
  # end
  # resources :comments
  # resources :books, only: [:index, :new, :create]
  # concern :commentable do 
  #   resources :comments 
  # end
  # resources :authors, concerns: :commentable
  # resources :books, concerns: :commentable
  # resources :authors do 
  #   member do 
  #     get 'preview'
  #   end
  # end
    # resources :authors do 
    # collection do 
    #   get 'preview'
    # end
    # get 'preview', on: :new

  # end
    # get 'authors(/:id)', to: 'authors#display'
   # get 'authors/:id/:user_id', to: 'authors#show'
  # get 'exit', to: 'sessions#destroy', as: :logout
  # match 'authors', to: 'authors#show', via: [:get, :post]
  # get 'authors/:id', to: 'authors#show', constraints: { id: /[A-Z]\d{5}/ }
# get 'authors/new', to: redirect('/authors')
# resources :authors

# resolve("Author") { [:author] }
# resources :photos, controller: 'authors'
# resources :user_permissions, controller: 'admin/authors'
# resources :authors, constraints: { id: /[A-Z][A-Z][0-9]+/ }
# resources :authors, as: 'images'
# resources :authors, path_names: { new: 'make', edit: 'change' }

# scope 'admin' do
#   resources :authors, as: 'admin_photos'
# end
# resources :authors
# scope ':username' do
#   resources :authors
# end
# resources :authors, only: [:index, :show]
# resources :authors, except: :destroy
# scope 'admin' do
#   resources :authors, as: 'admin_photos'
# end

# resources :authors
  # scope(path_names: { new: 'neu', edit: 'bearbeiten' }) do
  #   resources :authors, path: 'kategorien'
  # end
  # resources :authors, param: :identifier
   
end

app/models/admin/author.rb
module Admin
  class Author < ApplicationRecord
    has_many :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/admin/authors_controller.rb
module Admin
  class AuthorsController < ApplicationController
    def index
      @admin_authors = Author.all
      # redirect_to @admin_authors
      respond_to do |format|
        # format.json { show_json }
        format.html
      end
    end
    def show
      @author = Author.find(params[:id])
    end
    def new
      @author = Author.new
    end
  
    def create
      # @author = Author.new(name: "...", desc: "...")
  
      @author = Author.create!(authors_params)
      if @author.save
        redirect_to @author
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @author = Author.find(params[:id])
    end
  
    def update
      @author = Author.find(params[:id])
  
      if @author.update(author_params)
      redirect_to @author
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @author = Author.find(params[:id])
      @author.destroy

      redirect_to root_path, status: :see_other
    end
    def display 
    end


    private
    def author_params
      params.require(:author).permit(:name, :desc)
    end
    def authors_params
      params.require(:author).permit(:name, :desc, :price)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index 
    @books = Book.all
  end
  def create 
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/authors/_form.html.erb
<%= form_with model: author do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% author.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :desc %><br>
    <%= form.text_area :desc %><br>
    <% author.errors.full_messages_for(:desc).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %><br>
    <% author.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", author: @author %>

app/views/admin/authors/index.html.erb
<#% byebug %>
<h1>Authors</h1>

<ul>
  <% @admin_authors.each do |author| %>
    <li>
      <%= link_to author.name, author %>
    </li>
  <% end %>
</ul>
<%#= link_to "New Article", new_author_path %>

app/views/admin/authors/new.html.erb
<h1>New Article</h1>
<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @author.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :desc %><br>
    <%= form.text_area :desc %>
     <% @author.errors.full_messages_for(:desc).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %><br>
    <% @author.errors.full_messages_for(:price).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/authors/show.html.erb
<h1><%= @author.name %></h1>

<p><%= @author.desc %></p>

<ul>
  <li><%= link_to "Edit", edit_admin_author_path(@author) %></li>
  <li><%= link_to "Destroy", admin_author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/books/index.html.erb
<h1>Articles</h1>

<ul>
  <% @book.each do |book| %>
    <li>
      <%= link_to book.book_name, book %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>